Message.create!(greetings: 'Good Morning')
Message.create!(greetings: 'Good Afternoon')
Message.create!(greetings: 'Good Evening')
Message.create!(greetings: 'Ndewo')
Message.create!(greetings: 'Inakwana')