Message.create!(greeting: 'Good Morning')
Message.create!(greeting: 'Good Afternoon')
Message.create!(greeting: 'Good Evening')
Message.create!(greeting: 'Ndewo')
Message.create!(greeting: 'Inakwana')